name: Chexpert
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.4.26
  - certifi=2021.5.30
  - cycler=0.11.0
  - dataclasses=0.8
  - easydict=1.9
  - freetype=2.10.4
  - intel-openmp=2022.0.0
  - jbig=2.1
  - joblib=1.0.1
  - jpeg=9e
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  # - libcxx=14.0.6
  - libdeflate=1.7
  - libffi=3.3
  # - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.3.0
  - libuv=1.44.2
  - libwebp-base=1.2.4
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  # - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  # - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - pandas=1.1.5
  - pillow=8.3.2
  - pip=21.2.2
  - pyparsing=3.0.9
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytorch=1.8.1
  - pytz=2021.3
  # - readline=8.2
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.40.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchvision=0.2.2
  - tornado=6.1
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.0
